### ISSUE TITLE
Old CR/CRDs are not cleared when re-deploy zeta service on existing deployment, causing conflicts with new resources

### ISSUE THREAD

**Issue by liangbin-pub** [futurewei-cloud/zeta#57]
**Describe the bug**
CRD and CRs are not deleted when deploy Zeta operator

**To Reproduce**
1. full deployment with full_deploy.sh -d kind
2. then redeploy zeta services (may/may not after zeta code changes): zeta_deploy.sh -d kind
3. old CRD and CRs are not deleted

**Expected behavior**
Old CRs are deleted to avoid conflict with new deployment

**Additional context**
kubectl delete "$crd" --all. in create_crds.sh is missing -f when given a file, so basically the delete old CRD part is not effective.
Add back the -f the script will hang, because there are Finalizers Metadata
so the right way to delete CRs wold be patch CR, CRDs with Finalizers:[] first, then delete CRD,if that still not deletes CRs, delete CR first then CRD
example:
❯ kubectl get crds
NAME              CREATED AT
chains.zeta.com   2020-12-24T03:45:02Z
dfts.zeta.com     2020-12-24T03:45:03Z
ftns.zeta.com     2020-12-24T03:45:03Z
fwds.zeta.com     2020-12-24T03:45:03Z
❯ kubectl get fwd
NAME         STATUS        DFT    DROPLET                      CREATETIME                   PROVISIONDELAY
dft0-fwd-0   Provisioned   dft0   droplet-zgc-zeta-node-3      2020-12-24T03:45:57.138758   3679.235222
dft0-fwd-1   Provisioned   dft0   droplet-tenant-zeta-node-2   2020-12-24T03:45:57.145884   3679.225334
dft0-fwd-2   Provisioned   dft0   droplet-tenant-zeta-node-3   2020-12-24T03:45:57.151291   3679.271687
❯ kubectl delete fwd dft0-fwd-0
fwd.zeta.com "dft0-fwd-0" deleted.   <==== hangs
^C
❯ kubectl patch fwd/dft0-fwd-0 -p '{"metadata":{"finalizers":[]}}' --type=merge
❯ kubectl delete fwd dft0-fwd-0
❯ kubectl get fwd
NAME         STATUS        DFT    DROPLET                      CREATETIME                   PROVISIONDELAY
dft0-fwd-1   Provisioned   dft0   droplet-tenant-zeta-node-2   2020-12-24T03:45:57.145884   3679.225334
dft0-fwd-2   Provisioned   dft0   droplet-tenant-zeta-node-3   2020-12-24T03:45:57.151291   3679.271687
<===== successfully deleted CR without hang

===== Now patch all fwds CR and fwd CRD, then delete fwd CRD also deletes all fwd CRs
❯ kubectl patch fwd/dft0-fwd-1 -p '{"metadata":{"finalizers":[]}}' --type=merge
fwd.zeta.com/dft0-fwd-1 patched
❯ kubectl patch fwd/dft0-fwd-2 -p '{"metadata":{"finalizers":[]}}' --type=merge
fwd.zeta.com/dft0-fwd-2 patched
❯ kubectl patch crd/fwds.zeta.com -p '{"metadata":{"finalizers":[]}}' --type=merge
❯ kubectl delete crd fwds.zeta.com
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "fwds.zeta.com" not found
❯ kubectl get crds
NAME              CREATED AT
chains.zeta.com   2020-12-24T03:45:02Z
dfts.zeta.com     2020-12-24T03:45:03Z
ftns.zeta.com     2020-12-24T03:45:03Z
❯ kubectl get fwd
Error from server (NotFound): Unable to list "zeta.com/v1, Resource=fwds": the server could not find the requested resource (get fwds.zeta.com)

**Comment by zzxgzgz** [comment]
@liangbin-pub 

I tried to reproduce this error, but it was unsuccessful: 

Steps I took:

1. I added back the `-f` to the `kubectl delete "$crd" --all 2> /tmp/kubetctl.err`:
![image](https://user-images.githubusercontent.com/32083634/103234285-2383ea80-48f4-11eb-8d6e-470bc614b377.png)
2. I build Zeta and ran `full_deploy.sh -d kind`, which was successful:
```
...................

PLAY [==== provision Zeta Gateway Cluster] **********************************************************************************

PLAY RECAP ******************************************************************************************************************
localhost                  : ok=6    changed=3    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0

ubuntu@ip-172-31-15-115:~/src/github.com/zzxgzgz/zeta$ kubectl get crds
NAME                CREATED AT
chains.zeta.com     2020-12-28T18:10:38Z
dfts.zeta.com       2020-12-28T18:10:38Z
droplets.zeta.com   2020-12-28T18:10:38Z
ftns.zeta.com       2020-12-28T18:10:39Z
fwds.zeta.com       2020-12-28T18:10:39Z
ubuntu@ip-172-31-15-115:~/src/github.com/zzxgzgz/zeta$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
postgres-7875689b5-bqq7z         1/1     Running   0          2m14s
zeta-manager-8f95ddf9-vz27t      1/1     Running   0          84s
zeta-operator-69cb8695c4-cz5sr   1/1     Running   0          85s
```

3. Then I ran `zeta_deploy.sh -d kind`, CR/CRD deletion was successful, but redeploy failed:
```
TASK [Check Zeta deployment completion] *************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "../install/deploy_wellcheck.sh", "delta": "0:00:10.543729", "end": "2020-12-28 18:14:34.176017", "msg": "non-zero return code", "rc": 1, "start": "2020-12-28 18:14:23.632288", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   327  100   177  100   150   4317   3658 --:--:-- --:--:-- --:--:--  7975\nError response from daemon: endpoint with name zeta-node-3 already exists in network zgc_network", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", "100   327  100   177  100   150   4317   3658 --:--:-- --:--:-- --:--:--  7975", "Error response from daemon: endpoint with name zeta-node-3 already exists in network zgc_network"], "stdout": "Waiting for Operator to come up.\nZeta services are ready!", "stdout_lines": ["Waiting for Operator to come up.", "Zeta services are ready!"]}

PLAY RECAP ******************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

When getting the CRDs we can see from the `CREATED_AT` that the CRDs were re-applied successfully:
```
$ kubectl get crds
NAME                CREATED AT
chains.zeta.com     2020-12-28T18:13:40Z
dfts.zeta.com       2020-12-28T18:13:45Z
droplets.zeta.com   2020-12-28T18:13:51Z
ftns.zeta.com       2020-12-28T18:13:56Z
fwds.zeta.com       2020-12-28T18:14:02Z
```
To confirm this we can check in the ansible outputs:
```
Deleting old CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/chains.crd.yaml
customresourcedefinition.apiextensions.k8s.io "chains.zeta.com" deleted
Re-applying CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/chains.crd.yaml
customresourcedefinition.apiextensions.k8s.io/chains.zeta.com created
Deleting old CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/dfts.crd.yaml
customresourcedefinition.apiextensions.k8s.io "dfts.zeta.com" deleted
Re-applying CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/dfts.crd.yaml
customresourcedefinition.apiextensions.k8s.io/dfts.zeta.com created
Deleting old CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/droplets.crd.yaml
customresourcedefinition.apiextensions.k8s.io "droplets.zeta.com" deleted
Re-applying CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/droplets.crd.yaml
customresourcedefinition.apiextensions.k8s.io/droplets.zeta.com created
Deleting old CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/ftns.crd.yaml
customresourcedefinition.apiextensions.k8s.io "ftns.zeta.com" deleted
Re-applying CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/ftns.crd.yaml
customresourcedefinition.apiextensions.k8s.io/ftns.zeta.com created
Deleting old CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/fwds.crd.yaml
customresourcedefinition.apiextensions.k8s.io "fwds.zeta.com" deleted
Re-applying CRD: /home/ubuntu/src/github.com/zzxgzgz/zeta/deploy/etc/crds/fwds.crd.yaml
customresourcedefinition.apiextensions.k8s.io/fwds.zeta.com created
```

However, if I check each individual CRs, we can see that droplets weren't deployed successfully:
```
$ kubectl get droplets
No resources found in default namespace.
$ kubectl get chains
NAME           STATUS        HEAD                 TAIL                 DFT    SIZE   CREATETIME                   PROVISIONDELAY
dft0-chain-0   Provisioned   dft0-chain-0-ftn-0   dft0-chain-0-ftn-2   dft0   3      2020-12-28T18:14:06.912569   0.304256
dft0-chain-1   Provisioned   dft0-chain-1-ftn-0   dft0-chain-1-ftn-2   dft0   3      2020-12-28T18:14:06.925460   0.30993
dft0-chain-2   Provisioned   dft0-chain-2-ftn-0   dft0-chain-2-ftn-2   dft0   3      2020-12-28T18:14:06.935180   0.304581
$ kubectl get dfts
NAME   STATUS        NUMCHAINS   NUMCHAINREPLICAS   CREATETIME                   PROVISIONDELAY
dft0   Provisioned   3           3                  2020-12-28T18:14:06.579955   0.362699
$ kubectl get fwds
NAME         STATUS   DFT    DROPLET   CREATETIME                   PROVISIONDELAY
dft0-fwd-0   Init     dft0             2020-12-28T18:14:06.589756
dft0-fwd-1   Init     dft0             2020-12-28T18:14:06.594867
dft0-fwd-2   Init     dft0             2020-12-28T18:14:06.599632
$ kubectl get ftns
NAME                 STATUS   DFT    DROPLET   PARENTCHAIN    AUGMENTEDCHAIN   CREATETIME                   PROVISIONDELAY
dft0-chain-0-ftn-0   Init     dft0             dft0-chain-0                    2020-12-28T18:14:07.176358
dft0-chain-0-ftn-1   Init     dft0             dft0-chain-0                    2020-12-28T18:14:07.186284
dft0-chain-0-ftn-2   Init     dft0             dft0-chain-0                    2020-12-28T18:14:07.198345
dft0-chain-1-ftn-0   Init     dft0             dft0-chain-1                    2020-12-28T18:14:07.180980
dft0-chain-1-ftn-1   Init     dft0             dft0-chain-1                    2020-12-28T18:14:07.188932
dft0-chain-1-ftn-2   Init     dft0             dft0-chain-1                    2020-12-28T18:14:07.203983
dft0-chain-2-ftn-0   Init     dft0             dft0-chain-2                    2020-12-28T18:14:07.189566
dft0-chain-2-ftn-1   Init     dft0             dft0-chain-2                    2020-12-28T18:14:07.201254
dft0-chain-2-ftn-2   Init     dft0             dft0-chain-2                    2020-12-28T18:14:07.225021
```

So far CRs/CRDs can be deleted successfully, and most CRDs(except for droplets) can be re-created successfully. 

Am I missing some steps here? I am not getting the hang you experienced, and I am getting the re-deployment failure that you didn't get.

Thanks.

**Comment by liangbin-pub** [comment]
kubectl delete -f option fixed the issue
